name: Spack buildcache build

on: push

env:
  SPACK_COLOR: always
  SPACK_BACKTRACE: please

jobs:
  rebuild:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Spack
      run: |
        git clone --depth=1 --single-branch --branch fix/oci-parsing-uppercase https://github.com/haampie/spack.git
        echo "${PWD}/spack/bin/" >> "${GITHUB_PATH}"

    - name: Spack version
      run: spack debug report

    - name: Set authentication method for mirror
      run: |
        spack -e . mirror set --oci-username ${{ github.actor }} --oci-password "${{ secrets.GITHUB_TOKEN }}" local-buildcache

    - name: Concretize
      run: spack -e . concretize

    - name: Install
      run: |
        spack -e . env depfile -o Makefile
        make -Orecurse -j $(($(nproc) + 1)) SPACK_INSTALL_FLAGS=--no-check-signature

    - name: Push packages and update index
      run: |
        spack -e . buildcache push -j $(($(nproc) + 1)) --base-image ubuntu:22.04 --unsigned --update-index local-buildcache
      if: always()
